from miio import DeviceFactory
import time


def check(speed):
    input("Press enter when you feel the fan speed change.")
    time.sleep(2)
    start = time.time()
    if not fan.status().is_on:
        fan.on()
    fan.set_speed(speed)
    end = time.time()
    return end - start


fan = DeviceFactory.create("192.168.1.225", "647137208daf99bbc7d9103a085a6c8a")
fan.on()
fan.set_speed(0)
time.sleep(5)
print("interval 20")
print(check(20))
print(check(40))
print(check(60))
print(check(80))
print(check(100))
print("Wait...")
fan.set_speed(0)
fan.sleep(5)
print("interval 50")
print(check(50))
print(check(100))
print("Wait...")
fan.set_speed(0)
fan.off()
fan.sleep(5)
print("off to 20")
check(20)
print("Wait...")
fan.set_speed(0)
fan.off()
fan.sleep(5)
print("off to 50")
check(50)
print("Wait...")
fan.set_speed(0)
fan.off()
fan.sleep(5)
print("off to 100")
check(100)
fan.set_speed(100)
time.sleep(2)
print("interval -20")
print(check(80))
print(check(60))
print(check(40))
print(check(20))
print(check(0))
print("Wait...")
fan.set_speed(100)
fan.sleep(5)
print("interval -50")
print(check(50))
print(check(0))
print("Done.")
